/**
 * Learning path content for Mobilaws legal education
 * Content sourced from South Sudan law PDFs
 */

import { 
  getAllModules, 
  getModulesForTier, 
  getTopicById, 
  isTopicAccessible,
  type LegalTopic,
  type ExtractedModule 
} from './pdfContentExtractor';

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  locked?: boolean;
}

export interface Lesson {
  id: string;
  title: string;
  content: string;
  xpReward: number;
  quiz: QuizQuestion[];
  locked: boolean;
  completed: boolean;
  pdfSource?: string;
  tier: 'basic' | 'standard' | 'premium';
  hasAudio?: boolean; // Whether this lesson has audio/read-along feature
  userGenerated?: boolean; // Whether this lesson was generated by the user
  generationBatchId?: string; // ID of the generation batch this lesson belongs to
  createdAt?: any; // Creation timestamp (for grouping lessons by generation set)
}

export interface Module {
  id: string;
  title: string;
  description: string;
  icon: string;
  lessons: Lesson[];
  locked: boolean;
  requiredTier: 'free' | 'basic' | 'standard' | 'premium';
}

/**
 * Quiz questions for each topic
 */
const quizDatabase: Record<string, QuizQuestion[]> = {
  'const-intro-free': [
    {
      id: 'q0-1',
      question: 'What is the Constitution?',
      options: ['A book of stories', 'The highest law of the country', 'A history book', 'A government building'],
      correctAnswer: 1,
      explanation: 'The Constitution is the supreme law that governs how the country operates.'
    },
    {
      id: 'q0-2',
      question: 'Who does the Constitution protect?',
      options: ['Only government officials', 'Only rich people', 'Everyone in South Sudan', 'Only adults'],
      correctAnswer: 2,
      explanation: 'The Constitution protects the rights and freedoms of all people in South Sudan.'
    }
  ],
  'intl-intro-free': [
    {
      id: 'q0-3',
      question: 'What is international law?',
      options: ['Laws only for lawyers', 'Rules between countries', 'Laws about traveling', 'Court procedures'],
      correctAnswer: 1,
      explanation: 'International law consists of rules and agreements between countries.'
    }
  ],
  'penal-intro-free': [
    {
      id: 'q0-4',
      question: 'At what age can someone be charged with a crime in South Sudan?',
      options: ['Any age', '12 years', '18 years', '21 years'],
      correctAnswer: 1,
      explanation: 'In South Sudan, the age of criminal responsibility is 12 years.'
    },
    {
      id: 'q0-5',
      question: 'If you are arrested, what is one of your rights?',
      options: ['Right to remain silent', 'Must answer all questions', 'No rights until trial', 'Can only speak to police'],
      correctAnswer: 0,
      explanation: 'You have the right to remain silent and to have a lawyer present during questioning.'
    }
  ],
  'pub-intro-free': [
    {
      id: 'q0-6',
      question: 'What does "rule of law" mean?',
      options: [
        'Only citizens must follow laws',
        'Government and citizens must both follow laws',
        'Laws are optional',
        'Only the President makes laws'
      ],
      correctAnswer: 1,
      explanation: 'Rule of law means everyone, including the government, must follow the law.'
    }
  ],
  'const-intro': [
    {
      id: 'q1',
      question: 'What is the supreme law of South Sudan?',
      options: ['The Penal Code', 'The Constitution', 'Presidential Decrees', 'Customary Law'],
      correctAnswer: 1,
      explanation: 'The Constitution is the supreme law. All other laws must conform to it.'
    },
    {
      id: 'q2',
      question: 'In whom does sovereignty reside according to the Constitution?',
      options: ['The President', 'The Legislature', 'The People', 'The Courts'],
      correctAnswer: 2,
      explanation: 'Sovereignty resides in the people of South Sudan, who exercise it through their elected representatives.'
    }
  ],
  'const-rights': [
    {
      id: 'q3',
      question: 'Which document protects your fundamental rights?',
      options: ['Criminal Code', 'Bill of Rights', 'Civil Procedure', 'Land Act'],
      correctAnswer: 1,
      explanation: 'The Bill of Rights, part of the Constitution, protects fundamental rights and freedoms.'
    },
    {
      id: 'q4',
      question: 'What are economic and social rights?',
      options: [
        'Rights to buy and sell property only',
        'Rights to education, health, work, and property',
        'Rights for business owners only',
        'Rights that cost money to exercise'
      ],
      correctAnswer: 1,
      explanation: 'Economic and social rights include rights to education, health care, work, and property.'
    }
  ],
  'const-enforcement': [
    {
      id: 'q5',
      question: 'Which court has primary jurisdiction over constitutional matters?',
      options: ['Magistrate Court', 'High Court', 'Constitutional Court', 'Customary Court'],
      correctAnswer: 2,
      explanation: 'The Constitutional Court has primary jurisdiction over constitutional interpretation and enforcement.'
    },
    {
      id: 'q6',
      question: 'What is public interest litigation?',
      options: [
        'Litigation about public roads',
        'Court cases brought by government',
        'Legal action on behalf of wider community',
        'Cases heard in public'
      ],
      correctAnswer: 2,
      explanation: 'Public interest litigation allows legal action on behalf of groups or the wider community, not just individuals.'
    },
    {
      id: 'q7',
      question: 'Why are time limits important in constitutional cases?',
      options: [
        'Courts prefer quick cases',
        'To prevent stale claims and ensure timely justice',
        'Lawyers charge more for delayed cases',
        'Evidence is always lost'
      ],
      correctAnswer: 1,
      explanation: 'Time limits ensure timely justice and prevent parties from sitting on their rights. Constitutional remedies often have strict deadlines.'
    }
  ],
  'intl-intro': [
    {
      id: 'q8',
      question: 'Who are the primary subjects of international law?',
      options: ['Individuals', 'States', 'Corporations', 'NGOs'],
      correctAnswer: 1,
      explanation: 'States are the primary subjects of international law, though international organizations also have limited personality.'
    },
    {
      id: 'q9',
      question: 'What are the main sources of international law?',
      options: [
        'UN decisions only',
        'Treaties and customary law',
        'International newspapers',
        'World leaders\' speeches'
      ],
      correctAnswer: 1,
      explanation: 'Treaties and customary international law are the primary sources, along with general principles of law.'
    }
  ],
  'intl-treaties': [
    {
      id: 'q10',
      question: 'What does "pacta sunt servanda" mean?',
      options: [
        'Treaties are political documents',
        'Treaties must be performed in good faith',
        'Treaties can be broken easily',
        'Treaties only bind some parties'
      ],
      correctAnswer: 1,
      explanation: 'Pacta sunt servanda is a fundamental principle meaning treaties must be performed in good faith.'
    },
    {
      id: 'q11',
      question: 'Who ratifies international treaties in South Sudan?',
      options: ['The President alone', 'The National Legislature', 'The Supreme Court', 'The UN'],
      correctAnswer: 1,
      explanation: 'The National Legislature must ratify treaties after the President negotiates and signs them.'
    }
  ],
  'intl-state-responsibility': [
    {
      id: 'q12',
      question: 'When is conduct attributable to a State?',
      options: [
        'Only when the President acts',
        'When government officials or organs act',
        'Only in wartime',
        'Never - only individuals are responsible'
      ],
      correctAnswer: 1,
      explanation: 'Conduct of government officials and organs exercising government authority is attributable to the State.'
    },
    {
      id: 'q13',
      question: 'What are the three forms of reparation in international law?',
      options: [
        'Apology, fine, imprisonment',
        'Restitution, compensation, satisfaction',
        'Warning, sanction, expulsion',
        'Negotiation, mediation, arbitration'
      ],
      correctAnswer: 1,
      explanation: 'The three forms of reparation are restitution (restore situation), compensation (financial damages), and satisfaction (acknowledgment/apology).'
    },
    {
      id: 'q14',
      question: 'Which is a valid defense to state responsibility?',
      options: [
        'Economic difficulty',
        'Self-defense',
        'Political pressure',
        'Inconvenience'
      ],
      correctAnswer: 1,
      explanation: 'Self-defense is a valid defense, along with consent, force majeure, distress, and necessity under strict conditions.'
    }
  ],
  'intl-un-charter': [
    {
      id: 'q-intl-1',
      question: 'What is the primary purpose of the United Nations according to the Charter?',
      options: [
        'Economic development',
        'Maintain international peace and security',
        'Cultural exchange',
        'Sports competitions'
      ],
      correctAnswer: 1,
      explanation: 'The primary purpose of the UN is to maintain international peace and security, as stated in Article 1 of the Charter.'
    },
    {
      id: 'q-intl-2',
      question: 'How many members does the UN Security Council have?',
      options: ['10', '15', '20', '25'],
      correctAnswer: 1,
      explanation: 'The Security Council has 15 members: 5 permanent members (China, France, Russia, UK, USA) and 10 elected members.'
    }
  ],
  'intl-icj-statute': [
    {
      id: 'q-intl-3',
      question: 'How many judges serve on the International Court of Justice?',
      options: ['9', '12', '15', '18'],
      correctAnswer: 2,
      explanation: 'The ICJ has 15 judges elected by the UN General Assembly and Security Council for 9-year terms.'
    },
    {
      id: 'q-intl-4',
      question: 'What is required for the ICJ to have jurisdiction over a dispute?',
      options: [
        'Both states must be UN members',
        'States must consent to jurisdiction',
        'Dispute must involve human rights',
        'One state must be wealthy'
      ],
      correctAnswer: 1,
      explanation: 'The ICJ can only hear cases when states have consented to its jurisdiction, through special agreements, optional clause declarations, or treaty provisions.'
    }
  ],
  'intl-vienna-treaties': [
    {
      id: 'q-intl-5',
      question: 'What does "pacta sunt servanda" mean in treaty law?',
      options: [
        'Treaties can be broken',
        'Every treaty in force must be performed in good faith',
        'Only some treaties are binding',
        'Treaties expire after 10 years'
      ],
      correctAnswer: 1,
      explanation: 'Pacta sunt servanda means every treaty in force is binding upon the parties and must be performed by them in good faith.'
    },
    {
      id: 'q-intl-6',
      question: 'When can a state terminate a treaty due to material breach?',
      options: [
        'Never',
        'Only with consent of all parties',
        'When another party commits material breach',
        'Anytime it wants'
      ],
      correctAnswer: 2,
      explanation: 'A state can terminate or suspend a treaty if another party commits a material breach, but only in relation to that party.'
    }
  ],
  'intl-treaty-succession': [
    {
      id: 'q-intl-7',
      question: 'What is the "clean slate" principle for newly independent states?',
      options: [
        'They must accept all predecessor treaties',
        'They are not automatically bound by predecessor treaties',
        'They can only sign new treaties',
        'They lose all rights'
      ],
      correctAnswer: 1,
      explanation: 'The clean slate principle means newly independent states start fresh and are not automatically bound by the treaties of their predecessor state, though they may choose to succeed to some.'
    }
  ],
  'intl-subjects-states': [
    {
      id: 'q-intl-8',
      question: 'What are the four criteria for statehood under the Montevideo Convention?',
      options: [
        'Population, territory, government, recognition',
        'Population, territory, government, capacity to enter relations',
        'Wealth, military, population, territory',
        'UN membership, territory, government, population'
      ],
      correctAnswer: 1,
      explanation: 'The four criteria are: permanent population, defined territory, government, and capacity to enter into relations with other states.'
    },
    {
      id: 'q-intl-9',
      question: 'What is state immunity?',
      options: [
        'States never have to follow laws',
        'States are generally immune from jurisdiction of other states\' courts',
        'States cannot be sued',
        'States are above all law'
      ],
      correctAnswer: 1,
      explanation: 'State immunity means states are generally immune from the jurisdiction of other states\' courts, though there are exceptions for commercial activities and certain torts.'
    }
  ],
  'intl-subjects-orgs': [
    {
      id: 'q-intl-10',
      question: 'Why do international organizations have privileges and immunities?',
      options: [
        'To avoid taxes',
        'Functional necessity - to exercise their functions independently',
        'Because they are above the law',
        'To protect diplomats only'
      ],
      correctAnswer: 1,
      explanation: 'International organizations have immunities based on functional necessity - they need to be able to exercise their functions independently without interference from host states.'
    }
  ],
  'intl-diplomatic-relations': [
    {
      id: 'q-intl-11',
      question: 'What is the main function of a diplomatic mission?',
      options: [
        'Only to issue visas',
        'To represent the sending state and protect its interests',
        'To spy on the receiving state',
        'To collect taxes'
      ],
      correctAnswer: 1,
      explanation: 'The main functions include representing the sending state, protecting its interests and nationals, negotiating, and promoting friendly relations.'
    },
    {
      id: 'q-intl-12',
      question: 'What does "persona non grata" mean?',
      options: [
        'Welcome person',
        'Unacceptable person - can be expelled',
        'Diplomatic immunity',
        'Head of mission'
      ],
      correctAnswer: 1,
      explanation: 'Persona non grata means an unacceptable person. The receiving state can declare a diplomat persona non grata and require their removal.'
    }
  ],
  'intl-consular-relations': [
    {
      id: 'q-intl-13',
      question: 'What is a key difference between diplomatic and consular immunities?',
      options: [
        'Consular officers have more immunities',
        'Diplomatic officers have broader immunities than consular officers',
        'They are the same',
        'Only diplomats have immunities'
      ],
      correctAnswer: 1,
      explanation: 'Diplomatic officers have broader immunities, including complete immunity from criminal jurisdiction. Consular officers have more limited immunities, mainly for official acts.'
    },
    {
      id: 'q-intl-14',
      question: 'What is the right of consular officers regarding detained nationals?',
      options: [
        'No rights',
        'Right to visit and communicate with detained nationals',
        'Right to release them',
        'Right to represent them in court automatically'
      ],
      correctAnswer: 1,
      explanation: 'Consular officers have the right to visit and communicate with their detained nationals, and to arrange legal representation for them.'
    }
  ],
  'intl-responsibility': [
    {
      id: 'q-intl-15',
      question: 'What must a state do when it commits an internationally wrongful act?',
      options: [
        'Nothing',
        'Cease the act, offer non-repetition, and make reparation',
        'Only apologize',
        'Only pay money'
      ],
      correctAnswer: 1,
      explanation: 'A state must cease the wrongful act (if continuing), offer assurances of non-repetition, and make full reparation for any injury caused.'
    }
  ],
  'intl-dispute-settlement': [
    {
      id: 'q-intl-16',
      question: 'What is the difference between mediation and conciliation?',
      options: [
        'No difference',
        'Mediation is less formal; conciliation involves a commission making recommendations',
        'Mediation is binding; conciliation is not',
        'Only states use mediation'
      ],
      correctAnswer: 1,
      explanation: 'Mediation involves a third party facilitating negotiations. Conciliation is more formal, with a commission investigating and proposing settlement recommendations.'
    },
    {
      id: 'q-intl-17',
      question: 'What is required for the International Court of Justice to hear a case?',
      options: [
        'Both states must be UN members',
        'States must consent to ICJ jurisdiction',
        'The dispute must be about human rights',
        'One state must be from Europe'
      ],
      correctAnswer: 1,
      explanation: 'The ICJ requires consent to jurisdiction, which can be given through special agreements, optional clause declarations, treaty provisions, or forum prorogatum.'
    }
  ],
  'intl-peace-security': [
    {
      id: 'q-intl-18',
      question: 'What is the general rule on use of force in international law?',
      options: [
        'States can use force freely',
        'Threat or use of force is prohibited, except in self-defense or with UN authorization',
        'Only major powers can use force',
        'Force is allowed in economic disputes'
      ],
      correctAnswer: 1,
      explanation: 'Article 2(4) of the UN Charter prohibits threat or use of force, with exceptions for self-defense (Article 51) and UN Security Council authorization.'
    },
    {
      id: 'q-intl-19',
      question: 'What is the primary responsibility of the UN Security Council?',
      options: [
        'Economic development',
        'Maintain international peace and security',
        'Cultural preservation',
        'Sports coordination'
      ],
      correctAnswer: 1,
      explanation: 'The Security Council has primary responsibility for maintaining international peace and security under the UN Charter.'
    }
  ],
  'intl-human-rights': [
    {
      id: 'q-intl-20',
      question: 'What are the two main international human rights covenants?',
      options: [
        'Civil Rights and Political Rights',
        'ICCPR (Civil and Political) and ICESCR (Economic, Social, Cultural)',
        'Universal Declaration and Regional Charters',
        'UN Charter and Geneva Conventions'
      ],
      correctAnswer: 1,
      explanation: 'The two main covenants are the International Covenant on Civil and Political Rights (ICCPR) and the International Covenant on Economic, Social and Cultural Rights (ICESCR).'
    },
    {
      id: 'q-intl-21',
      question: 'What is the principle of non-refoulement?',
      options: [
        'States can return anyone',
        'Cannot return person to country where they face persecution',
        'Must return all refugees',
        'Only applies to criminals'
      ],
      correctAnswer: 1,
      explanation: 'Non-refoulement prohibits returning a person to a country where they would face persecution, torture, or other serious harm.'
    }
  ],
  'intl-migration-refugees': [
    {
      id: 'q-intl-22',
      question: 'What is the difference between a refugee and an internally displaced person?',
      options: [
        'No difference',
        'Refugee crosses international border; IDP remains in own country',
        'Refugee has more rights',
        'IDP has more rights'
      ],
      correctAnswer: 1,
      explanation: 'A refugee has crossed an international border and is protected by refugee law. An IDP is forced to flee but remains within their own country.'
    },
    {
      id: 'q-intl-23',
      question: 'What is statelessness?',
      options: [
        'Having two nationalities',
        'Not being recognized as a national by any state',
        'Living abroad',
        'Being a refugee'
      ],
      correctAnswer: 1,
      explanation: 'A stateless person is someone who is not considered a national by any state under its laws, leaving them without the protection of any state.'
    }
  ],
  'penal-intro': [
    {
      id: 'q15',
      question: 'What two elements are required for most crimes?',
      options: ['Victim and Witness', 'Act and Intent (actus reus and mens rea)', 'Arrest and Trial', 'Judge and Jury'],
      correctAnswer: 1,
      explanation: 'Most crimes require both a guilty act (actus reus) and guilty mind (mens rea).'
    },
    {
      id: 'q16',
      question: 'What is the age of criminal responsibility in South Sudan?',
      options: ['10 years', '12 years', '14 years', '18 years'],
      correctAnswer: 1,
      explanation: 'The age of criminal responsibility in South Sudan is 12 years under the Penal Code.'
    }
  ],
  'penal-defenses': [
    {
      id: 'q17',
      question: 'Which of these is a complete defense to a criminal charge?',
      options: ['Poverty', 'Insanity', 'Ignorance of law', 'Peer pressure'],
      correctAnswer: 1,
      explanation: 'Insanity is a complete defense if the accused lacked understanding due to mental disorder.'
    },
    {
      id: 'q18',
      question: 'What is required for self-defense to be valid?',
      options: [
        'Any force is allowed',
        'Force must be proportional and reasonable',
        'Must have a weapon',
        'Must be defending property only'
      ],
      correctAnswer: 1,
      explanation: 'Self-defense must use proportional and reasonable force. Excessive force is not justified.'
    },
    {
      id: 'q19',
      question: 'Who has the burden of proof in a criminal case?',
      options: [
        'The accused must prove innocence',
        'The prosecution must prove guilt beyond reasonable doubt',
        'The judge decides without proof',
        'Both sides equally'
      ],
      correctAnswer: 1,
      explanation: 'The prosecution must prove guilt beyond reasonable doubt. The accused is presumed innocent.'
    }
  ],
  'penal-procedure': [
    {
      id: 'q20',
      question: 'Within what time must an arrested person be brought before court?',
      options: ['24 hours', '48 hours', '72 hours', '1 week'],
      correctAnswer: 0,
      explanation: 'An arrested person must be brought before a court within 24 hours.'
    },
    {
      id: 'q21',
      question: 'What should you do if arrested?',
      options: [
        'Answer all questions immediately',
        'Cooperate but request a lawyer before answering substantive questions',
        'Run away',
        'Confess to avoid trouble'
      ],
      correctAnswer: 1,
      explanation: 'You should cooperate with police but request a lawyer before answering substantive questions. You have the right to remain silent.'
    },
    {
      id: 'q22',
      question: 'What is the purpose of bail?',
      options: [
        'To punish the accused',
        'To ensure accused appears for trial',
        'To raise money for government',
        'To decide guilt'
      ],
      correctAnswer: 1,
      explanation: 'Bail ensures the accused will appear for trial while respecting the presumption of innocence.'
    },
    {
      id: 'q23',
      question: 'Within what time must an appeal be filed?',
      options: ['7 days', '14 days', '30 days', '90 days'],
      correctAnswer: 2,
      explanation: 'Appeals must typically be filed within 30 days of judgment.'
    }
  ],
  'pub-intro': [
    {
      id: 'q24',
      question: 'What does the separation of powers mean?',
      options: [
        'Different levels of government',
        'Executive, Legislative, and Judicial branches are independent',
        'Only the President has power',
        'States have more power than federal government'
      ],
      correctAnswer: 1,
      explanation: 'Separation of powers means the Executive, Legislative, and Judicial branches are independent and check each other.'
    }
  ],
  'pub-admin': [
    {
      id: 'q25',
      question: 'What is judicial review?',
      options: [
        'Judge reviewing case files',
        'Courts reviewing lawfulness of government decisions',
        'Reviewing judge performance',
        'Public reviewing court decisions'
      ],
      correctAnswer: 1,
      explanation: 'Judicial review is when courts review the lawfulness of government decisions for legality, rationality, and procedural fairness.'
    },
    {
      id: 'q26',
      question: 'What does "ultra vires" mean?',
      options: [
        'Very strong',
        'Beyond legal powers',
        'Under authority',
        'Within limits'
      ],
      correctAnswer: 1,
      explanation: '"Ultra vires" means beyond legal powers - when a government body acts without legal authority.'
    },
    {
      id: 'q27',
      question: 'What is a mandamus order?',
      options: [
        'Order to stop action',
        'Order to perform a legal duty',
        'Order to pay damages',
        'Order to arrest someone'
      ],
      correctAnswer: 1,
      explanation: 'Mandamus is a court order compelling a government body to perform a legal duty.'
    }
  ],
  'pub-practice': [
    {
      id: 'q28',
      question: 'What should you do before filing a judicial review application?',
      options: [
        'Go straight to court',
        'Write to government body requesting reconsideration',
        'Protest publicly',
        'Wait one year'
      ],
      correctAnswer: 1,
      explanation: 'You should first write to the government body outlining concerns and requesting reconsideration before going to court.'
    },
    {
      id: 'q29',
      question: 'What is required for standing in judicial review?',
      options: [
        'Must be a lawyer',
        'Must have sufficient interest in the matter',
        'Must be a government employee',
        'Must be wealthy'
      ],
      correctAnswer: 1,
      explanation: 'You must have sufficient interest in the matter - be affected by the decision or have legitimate concern.'
    },
    {
      id: 'q30',
      question: 'Why should you act quickly when challenging government action?',
      options: [
        'Judges prefer quick cases',
        'Judicial review has strict time limits',
        'Evidence is always destroyed',
        'Lawyers are cheaper early'
      ],
      correctAnswer: 1,
      explanation: 'Judicial review applications must usually be filed within 3-6 months. Time limits are strict.'
    },
    {
      id: 'q31',
      question: 'What is public interest litigation?',
      options: [
        'Litigation about public property',
        'Legal action on behalf of wider community or public good',
        'Cases heard in public',
        'Government prosecutions'
      ],
      correctAnswer: 1,
      explanation: 'Public interest litigation allows legal action on behalf of the wider community or public good, not just individual interests.'
    }
  ]
};

/**
 * Module icons by category - using FontAwesome icon names
 */
const moduleIcons: Record<string, string> = {
  constitution: 'faScroll',
  'international-law': 'faGlobe',
  'criminal-law': 'faScaleBalanced',
  'public-law': 'faLandmark'
};

/**
 * XP rewards by tier
 */
const xpByTier: Record<string, number> = {
  basic: 10,
  standard: 20,
  premium: 50
};

/**
 * Convert extracted PDF topics to lessons
 */
function topicToLesson(topic: LegalTopic, userTier: 'free' | 'basic' | 'standard' | 'premium', lessonIndex: number, totalLessons: number): Lesson {
  const accessible = isTopicAccessible(topic.id, userTier);
  const quiz = quizDatabase[topic.id] || [];
  
  // Determine if lesson should have audio
  let hasAudio = false;
  if (accessible) {
    if (userTier === 'premium') {
      // Premium: All lessons have audio
      hasAudio = true;
    } else if (userTier === 'standard') {
      // Standard: 30% of lessons have audio (approximately every 3rd lesson)
      // Calculate which lessons get audio (30% = roughly 1 in 3)
      const audioInterval = Math.ceil(totalLessons / (totalLessons * 0.3));
      hasAudio = (lessonIndex + 1) % audioInterval === 0 || lessonIndex === 0; // First lesson + every Nth
    }
    // Basic and free: No audio
  }
  
  // Don't show upgrade message for premium users
  const lockedContent = userTier === 'premium' 
    ? `This lesson is available in ${topic.tier.toUpperCase()} subscription.\n\nContent: ${topic.description}`
    : `🔒 This lesson is available in ${topic.tier.toUpperCase()} subscription.\n\nUpgrade to unlock detailed content about: ${topic.description}`;
  
  return {
    id: topic.id,
    title: topic.title,
    content: accessible ? topic.content : lockedContent,
    xpReward: accessible ? xpByTier[topic.tier] : 0,
    quiz: accessible ? quiz : [],
    locked: !accessible,
    completed: false,
    pdfSource: undefined, // Remove PDF source from lessons
    tier: topic.tier,
    hasAudio: hasAudio
  };
}

/**
 * Get learning modules for user's subscription tier
 * NOW RETURNS EMPTY - All modules should come from Firestore (tutor admin generated)
 */
export function getLearningModules(userTier: 'free' | 'basic' | 'standard' | 'premium' = 'free'): Module[] {
  // Return empty array - all content should come from Firestore via tutor admin
  // The LearningContext should fetch modules from the backend API instead
  console.log('⚠️ getLearningModules() called but returning empty - use Firestore modules instead');
  return [];
}

/**
 * Default export for backwards compatibility
 * NOW EMPTY - All modules from Firestore
 */
export const learningModules: Module[] = [];
