import { useMemo } from 'react';
import { Download, Award, AlertTriangle, Lightbulb, BarChart3, Scale, ShieldCheck, Brain, BookOpen } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { type SessionEvaluation, type Interruption, type EmotionSnapshot } from '@/contexts/CourtSimulatorContext';

interface ScoreDashboardProps {
  evaluation: SessionEvaluation;
  transcript: string;
  interruptions: Interruption[];
  emotionTimeline: EmotionSnapshot[];
  durationSeconds: number;
}

const DIMENSION_META: Record<string, { label: string; color: string }> = {
  legal_reasoning: { label: 'Legal Reasoning', color: '#3b82f6' },
  legal_accuracy: { label: 'Legal Accuracy', color: '#6366f1' },
  credibility: { label: 'Credibility', color: '#ec4899' },
  clarity: { label: 'Clarity', color: '#10b981' },
  logical_consistency: { label: 'Logical Consistency', color: '#8b5cf6' },
  emotional_control: { label: 'Emotional Control', color: '#f59e0b' },
};

export default function ScoreDashboard({
  evaluation,
  transcript,
  interruptions,
  emotionTimeline,
  durationSeconds,
}: ScoreDashboardProps) {
  const overallGrade = useMemo(() => {
    const s = evaluation.overall_score;
    if (s >= 90) return { letter: 'A+', color: 'text-green-600', bg: 'bg-green-50' };
    if (s >= 80) return { letter: 'A', color: 'text-green-600', bg: 'bg-green-50' };
    if (s >= 70) return { letter: 'B', color: 'text-blue-600', bg: 'bg-blue-50' };
    if (s >= 60) return { letter: 'C', color: 'text-yellow-600', bg: 'bg-yellow-50' };
    if (s >= 50) return { letter: 'D', color: 'text-orange-600', bg: 'bg-orange-50' };
    return { letter: 'F', color: 'text-red-600', bg: 'bg-red-50' };
  }, [evaluation.overall_score]);

  const dimensions = [
    { key: 'legal_reasoning', score: evaluation.legal_reasoning },
    { key: 'legal_accuracy', score: evaluation.legal_accuracy || 0 },
    { key: 'credibility', score: evaluation.credibility || 0 },
    { key: 'clarity', score: evaluation.clarity },
    { key: 'logical_consistency', score: evaluation.logical_consistency },
    { key: 'emotional_control', score: evaluation.emotional_control },
  ];

  const handleDownload = () => {
    const lines = [
      'REPUBLIC OF SOUTH SUDAN',
      'AI COURT SIMULATION - JUDICIAL EVALUATION REPORT',
      '='.repeat(55),
      '',
      `Date: ${new Date().toLocaleDateString()}`,
      `Duration: ${Math.floor(durationSeconds / 60)}m ${durationSeconds % 60}s`,
      `Overall Score: ${evaluation.overall_score}/100 (${overallGrade.letter})`,
      `Judicial Interruptions: ${interruptions.length}`,
      '',
      'SCORES',
      '-'.repeat(40),
      ...dimensions.map(d => {
        const meta = DIMENSION_META[d.key];
        return `  ${meta.label}: ${d.score}/100`;
      }),
      '',
      'JUDICIAL SUMMARY',
      '-'.repeat(40),
      evaluation.summary,
      '',
      'APPLICABLE LEGAL REFERENCES',
      '-'.repeat(40),
      ...(evaluation.legal_references?.length
        ? evaluation.legal_references.map(r => `  - ${r}`)
        : ['  (No specific references identified)']),
      '',
      'QUOTED LEGAL PROVISIONS',
      '-'.repeat(40),
      ...(evaluation.legal_quotes?.length
        ? evaluation.legal_quotes.flatMap((item, i) => [
          `  ${i + 1}. ${item.reference}`,
          `     Quote: ${item.quote}`,
          `     Relevance: ${item.relevance || '(No relevance note provided)'}`,
        ])
        : ['  (No legal provision quotes available)']),
      '',
      'CREDIBILITY ASSESSMENT',
      '-'.repeat(40),
      evaluation.credibility_assessment || '(Not assessed)',
      '',
      'EMOTIONAL PROFILE',
      '-'.repeat(40),
      evaluation.emotion_profile || '(Not assessed)',
      '',
      'STRENGTHS',
      '-'.repeat(40),
      ...evaluation.strengths.map(s => `  + ${s}`),
      '',
      'WEAKNESSES',
      '-'.repeat(40),
      ...evaluation.weaknesses.map(w => `  - ${w}`),
      '',
      'RECOMMENDATIONS',
      '-'.repeat(40),
      ...evaluation.recommendations.map((r, i) => `  ${i + 1}. ${r}`),
      '',
      'FULL TRANSCRIPT',
      '-'.repeat(40),
      transcript || '(No transcript recorded)',
      '',
      '='.repeat(55),
      'Generated by Mobilaws Court Simulator',
      'Based on the Transitional Constitution of South Sudan, 2011',
      'and the Penal Code Act of South Sudan, 2008',
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `court-simulation-report-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-2xl mx-auto space-y-5 p-4 sm:p-6">
      {/* Overall Score */}
      <div className="text-center">
        <div className={`inline-flex flex-col items-center ${overallGrade.bg} rounded-2xl px-8 py-6`}>
          <span className={`text-6xl font-bold ${overallGrade.color}`}>
            {evaluation.overall_score}
          </span>
          <span className={`text-2xl font-semibold ${overallGrade.color} mt-1`}>
            {overallGrade.letter}
          </span>
          <span className="text-gray-500 text-sm mt-1">Overall Score</span>
        </div>
      </div>

      {/* Dimension Scores — 2 col grid */}
      <div className="grid grid-cols-2 gap-3">
        {dimensions.map(({ key, score }) => {
          const meta = DIMENSION_META[key];
          return (
            <div key={key} className="bg-white border border-gray-100 rounded-xl p-3 shadow-sm">
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-[11px] font-medium text-gray-500">{meta.label}</span>
                <span className="text-lg font-bold" style={{ color: meta.color }}>{score}</span>
              </div>
              <div className="w-full h-2 bg-gray-100 rounded-full overflow-hidden">
                <div
                  className="h-full rounded-full transition-all duration-700"
                  style={{ width: `${score}%`, backgroundColor: meta.color }}
                />
              </div>
            </div>
          );
        })}
      </div>

      {/* Judicial Summary */}
      <div className="bg-gray-50 rounded-xl p-4">
        <div className="flex items-center gap-2 mb-2">
          <BarChart3 className="h-4 w-4 text-gray-600" />
          <h4 className="font-semibold text-gray-800">Judicial Summary</h4>
        </div>
        <p className="text-gray-700 text-sm leading-relaxed">{evaluation.summary}</p>
      </div>

      {/* Applicable Legal References */}
      {evaluation.legal_references && evaluation.legal_references.length > 0 && (
        <div className="bg-indigo-50 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <BookOpen className="h-4 w-4 text-indigo-600" />
            <h4 className="font-semibold text-indigo-800">Applicable Legal References</h4>
          </div>
          <ul className="space-y-1.5">
            {evaluation.legal_references.map((ref, i) => (
              <li key={i} className="text-indigo-700 text-sm flex items-start gap-2">
                <Scale className="h-3.5 w-3.5 text-indigo-400 mt-0.5 shrink-0" />
                {ref}
              </li>
            ))}
          </ul>
          <p className="text-[10px] text-indigo-400 mt-2 italic">
            Based on the Transitional Constitution of South Sudan, 2011 & Penal Code Act, 2008
          </p>
        </div>
      )}

      {/* Quoted Legal Provisions */}
      {evaluation.legal_quotes && evaluation.legal_quotes.length > 0 && (
        <div className="bg-violet-50 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <Scale className="h-4 w-4 text-violet-600" />
            <h4 className="font-semibold text-violet-800">Quoted Legal Provisions</h4>
          </div>
          <ul className="space-y-3">
            {evaluation.legal_quotes.map((item, i) => (
              <li key={i} className="text-violet-800 text-sm">
                <p className="font-semibold">{item.reference}</p>
                <p className="italic text-violet-700 mt-1">{item.quote}</p>
                {item.relevance && (
                  <p className="text-violet-700 mt-1">{item.relevance}</p>
                )}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Credibility Assessment */}
      {evaluation.credibility_assessment && (
        <div className="bg-pink-50 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <ShieldCheck className="h-4 w-4 text-pink-600" />
            <h4 className="font-semibold text-pink-800">Credibility Assessment</h4>
            <span className="ml-auto text-sm font-bold text-pink-600">{evaluation.credibility || 0}/100</span>
          </div>
          <p className="text-pink-700 text-sm leading-relaxed">{evaluation.credibility_assessment}</p>
        </div>
      )}

      {/* Emotional Profile */}
      {evaluation.emotion_profile && (
        <div className="bg-amber-50 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <Brain className="h-4 w-4 text-amber-600" />
            <h4 className="font-semibold text-amber-800">Emotional Profile</h4>
            <span className="ml-auto text-sm font-bold text-amber-600">{evaluation.emotional_control}/100</span>
          </div>
          <p className="text-amber-700 text-sm leading-relaxed">{evaluation.emotion_profile}</p>
        </div>
      )}

      {/* Strengths */}
      <div className="bg-green-50 rounded-xl p-4">
        <div className="flex items-center gap-2 mb-2">
          <Award className="h-4 w-4 text-green-600" />
          <h4 className="font-semibold text-green-800">Strengths</h4>
        </div>
        <ul className="space-y-1.5">
          {evaluation.strengths.map((s, i) => (
            <li key={i} className="text-green-700 text-sm flex items-start gap-2">
              <span className="text-green-500 mt-0.5">+</span>
              {s}
            </li>
          ))}
        </ul>
      </div>

      {/* Weaknesses */}
      <div className="bg-orange-50 rounded-xl p-4">
        <div className="flex items-center gap-2 mb-2">
          <AlertTriangle className="h-4 w-4 text-orange-600" />
          <h4 className="font-semibold text-orange-800">Areas for Improvement</h4>
        </div>
        <ul className="space-y-1.5">
          {evaluation.weaknesses.map((w, i) => (
            <li key={i} className="text-orange-700 text-sm flex items-start gap-2">
              <span className="text-orange-500 mt-0.5">-</span>
              {w}
            </li>
          ))}
        </ul>
      </div>

      {/* Recommendations */}
      <div className="bg-blue-50 rounded-xl p-4">
        <div className="flex items-center gap-2 mb-2">
          <Lightbulb className="h-4 w-4 text-blue-600" />
          <h4 className="font-semibold text-blue-800">Recommendations</h4>
        </div>
        <ol className="space-y-1.5">
          {evaluation.recommendations.map((r, i) => (
            <li key={i} className="text-blue-700 text-sm flex items-start gap-2">
              <span className="text-blue-400 font-medium min-w-[16px]">{i + 1}.</span>
              {r}
            </li>
          ))}
        </ol>
      </div>

      {/* Session Stats */}
      <div className="flex items-center justify-between text-xs text-gray-400 px-1">
        <span>Duration: {Math.floor(durationSeconds / 60)}m {durationSeconds % 60}s</span>
        <span>Interruptions: {interruptions.length}</span>
        <span>Emotion points: {emotionTimeline.length}</span>
      </div>

      {/* Download */}
      <Button onClick={handleDownload} variant="outline" className="w-full">
        <Download className="h-4 w-4 mr-2" />
        Download Full Report
      </Button>
    </div>
  );
}
